### ISSUE TITLE
Build failed when run the app

### ISSUE THREAD

**Issue by MustafaDeniz23** [amake/flutter_charset_detector#2]
I added flutter_charset_detector: ^0.3.0 to my pubspec.yaml. And there was no problem when i wrote "pub get" on the terminal. But i tried to run the app, and because of the following exception, the build failed. 

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: C:\Users\Dexter\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_charset_detector-0.3.0\android\src\main\kotlin\com\madlonkay\flutter_charset_detector\FlutterCharsetDetectorPlugin.kt: (58, 36): Expecting an argument

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_charset_detector:compileDebugKotlin'.
```

What should i do? Thanks a lot.

**Comment by amake** [comment]
See #1. Your choices are:

- Update your Kotlin to 1.3.70 or later
- Use flutter_charset_detector 1.01
