### ISSUE TITLE
would you please provide another API to fast detect encoding only?

### ISSUE THREAD

**Issue by Hilbert2048** [amake/flutter_charset_detector#8]
For instance, to rapidly identify the encoding of a large file, follow these steps:

1、Read a sample portion of the file's data.
2、Utilize a fast encoding detection API.
3、Return only the encoding result. It's unnecessary to return the data associated with the encoding because the fixed-size sample data buffer might not successfully decode

**Comment by amake** [comment]
I've just released updates with a new `detect` method that returns only the detected charset without trying to decode the supplied bytes.
